services:
  grocy:
    image: lscr.io/linuxserver/grocy
    container_name: grocy
    hostname: grocy
    environment:
      - PUID=${PUID}
      - PGID=$PUID}
      - TZ=${TIMEZONE}
    volumes:
      - ${GROCY_CONFIG_FOLDER}:/config
    restart: unless-stopped
    networks:
      external:
        ipv4_address: ${GROCY_IP_ADDRESS}

networks:
  external:
    external: true
    name: ${EXTERNAL_NETWORK_NAME}